[package]
name = "deepwalk"
version = "0.1.0"
authors = ["Alex Puzyk <APuzyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
nalgebra = "0.21.1"
itertools = "0.8.0"
rayon = "1.4.0"
